import mongoose from "mongoose";
import ProductModel from "./productmodels.js";
import User from "./userModel.js";
import { request } from "express";

const orderSchemaModel = new mongoose.Schema({
    shippingAddress:{
        address:{
            type:String,
            required:true
        },
         city:{
            type:String,
            required:true
        },
         state:{
            type:String,
            required:true
        },
         country:{
            type:String,
            required:true
        },
         pinCode:{
            type:Number,
            required:true
        },
        contactNumber:{
            type:Number,
            required:true
        },
       },
       orderItems:[
        {
            name:{
            type:String,
            required:true
        },
         price:{
            type:Number,
            required:true
        },
        quantity:{
            type:Number,
            required:true
        },
        image:{
            type:String,
            required:true
        },
        product:{
            type:mongoose.Schema.ObjectId,
            ref: "ProductModel",
            required:true,
        },
        },
       ],
       orderStatus:{
           type:String,
           required:true,
           default:"Processing",
       },
       user:{
         type:mongoose.Schema.ObjectId,
         ref:"User",
         required:true,
       },
       paymentInfo:{
        id:{
            type:String,
            required:true
        },
        status:{
             type:String,
            required:true
        },
    },
       paidAt:{
             type:Date,
            required:true
       },
        productPrice:{
            type:Number,
            required:true,
            default:0
        },
        taxPrice:{
            type:Number,
            required:true,
            default:0
        },
        ShippingPrice:{
            type:Number,
            required:true,
            default:0
        },
        totalPrice:{
            type:Number,
            required:true,
            default:0
        },
        deliveredAt:Date,
        createdAt:{
            type:Date,
            default:Date.now
        }
       
})

export default mongoose.model("Order",orderSchemaModel);